// <auto-generated />
using System;
using KVS_API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KVS_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KVS_API.Models.Konto", b =>
                {
                    b.Property<string>("Kontonummer")
                        .HasColumnType("text")
                        .HasColumnName("kontonummer");

                    b.Property<DateTime>("Erstelltam")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("erstelltam");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("typ");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("userid");

                    b.HasKey("Kontonummer");

                    b.HasIndex("UserId");

                    b.ToTable("konten", (string)null);

                    b.HasDiscriminator<string>("Typ").HasValue("Konto");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("KVS_API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime>("Erstelltam")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("erstelltam");

                    b.Property<string>("Passwordhash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("passwordhash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("KVS_API.Models.Privatkonto", b =>
                {
                    b.HasBaseType("KVS_API.Models.Konto");

                    b.HasDiscriminator().HasValue("Privatkonto");
                });

            modelBuilder.Entity("KVS_API.Models.Sparkonto", b =>
                {
                    b.HasBaseType("KVS_API.Models.Konto");

                    b.HasDiscriminator().HasValue("Sparkonto");
                });

            modelBuilder.Entity("KVS_API.Models.Konto", b =>
                {
                    b.HasOne("KVS_API.Models.User", "User")
                        .WithMany("Konten")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("KVS_API.Models.User", b =>
                {
                    b.Navigation("Konten");
                });
#pragma warning restore 612, 618
        }
    }
}
